name: Node.js Build & Test

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

jobs:
  build:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    name: Node Build & Test
    env:
      ENV: ${{ secrets.ENV }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: echo "$ENV" > .env
      - run: yarn install
      - run: yarn test

