name: Workflows with large secrets

on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.ENV }}
        run: |
          echo "$SUPER_SECRET"
          echo "$SUPER_SECRET" >> test.txt
          ls -la
          cat test.txt
