name: Node.js Build, Test, and Deploy

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          CUSTO: ${{ secrets.CUSTO }}
       - run: echo ${{ secrets.ENV }} > .env
       - run: echo ${{ secrets.ENV }}
#      - run: touch .env
#      - run: echo ${{ secrets.ENV }} >> .env
#      - run: echo 'rogue' >> .env
#      - run: ls -la
#      - run: cat .env
#      - run: yarn install
#      - run: yarn test

