name: Node.js Build, Test, and Deploy

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Prepare .env file
        env:
          ENV: ${{ secrets.ENV }}
        run: |
          echo "$ENV"
          echo "$ENV" > .env
          ls -la
          cat .env
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: yarn install
    - run: yarn test
