name: Node.js Test, Build and Notify

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        env:
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ENV: ${{ secrets.ENV }}
      - run: echo "$MONGODB_URL" > .env
      - run: echo "$JWT_SECRET" >> .env
      - run: echo $ENV >> .env
      - run: echo 'Lorem Ipsum' >> .env
      - run: ls -la
      - run: cat .env
      #- run: yarn install
      #- run: yarn test

