name: Node.js Build, Test, and Deploy

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare .env file
        env:
          ENV: ${{ secrets.ENV }}
        run: |
          echo "$ENV"
          echo "$ENV" > .env
          ls -la
          cat .env

  build:
    runs-on: ubuntu-latest
    name: Node Build & Test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      run: |
        yarn install
        yarn test
