name: Node.js Build, Test, and Deploy

on:
  push:
    branches: [ staging, master ]
  pull_request:
    branches: [ staging, master ]

jobs:
  build:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    name: Node Build & Test
    env:
      ENV: ${{ secrets.ENV }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: echo "$ENV" > .env
      - run: yarn install
      - run: yarn test

  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Deploy to the prod server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: cd ${{ secrets.SERVER_PATH }} && sh scripts/deploy.sh
