name: Node.js Build, Test, and Deploy

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.ENV }}
        run: |
          echo "$SUPER_SECRET"
          echo "$SUPER_SECRET" >> .env
          ls -la
          cat .env

